name: Node.js CI/CD

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Update with your desired Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh-keyscan -H 185.217.131.146 >> ~/.ssh/known_hosts
          ssh root@185.217.131.146 'bash -s' <<'EOF'
          mkdir -p /auto_deploy_nestjs  # Ensure directory exists
          cd /auto_deploy_nestjs
          git pull https://github.com/farzot/nest_ci_cd.git
          npm install
          npm run build
          pm2 restart 3
          EOF
